### ISSUE TITLE
 compile error

### ISSUE THREAD

**Issue by baozeng90** [eProsima/Micro-XRCE-DDS#19]
/home/ros2/Micro-XRCE-DDS-Agent/include/micrortps/agent/datawriter/DataWriter.hpp:62:21: error: cannot declare field ‘eprosima::micrortps::DataWriter::topic_type_’ to be of abstract type ‘eprosima::micrortps::TopicPubSubType’
     TopicPubSubType topic_type_;

**Comment by BorjaOuterelo** [comment]
Hi @baozeng90 

Can you provide us with more information on your compilation environment?:

- Which version of Micro XRCE-DDS Agent are you trying to compile?
- Against which version of Fast RTPS are you compiling?
- Which compilation command are you launching?

**Comment by ross-desmond** [comment]
I am having the same issue. I believe this is due to using FastRTPS 1.7.0 with Micro-XRCE-DDS on master. The "Agent" repo link needs to be updated to master for micro xrce to compile with FastRTPS 1.7.0.

**Comment by baozeng90** [comment]
> I am having the same issue. I believe this is due to using FastRTPS 1.7.0 with Micro-XRCE-DDS on master. The "Agent" repo link needs to be updated to master for micro xrce to compile with FastRTPS 1.7.0.

yes,I'm using FastRTPS 1.7.0 with Micro-XRCE-DDS,if use FastRTPS in Micro-XRCE-DDS/agent/thirdparty/fastrtps,it si OK!So I think The  versions should be the same(ROS2 and Micro-XRCE-DDS's FastRTPS).

**Comment by BorjaOuterelo** [comment]
Yes, this is an issue due to the use of Fast RTPS 1.7.0.

I have merged a PR into Micro XRCE-DDS Agent fixing these incompatibilities with Fast RTPS 1.7.0.
PR: https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/42

If you update your Micro XRCE-DDS Agent master branch, it should not cause these compilation errors.

**Comment by baozeng90** [comment]
Thankyou
